// This file is generated by scripts/generate-reference-artifacts.mjs. Do not edit.

export const BANNED_PHRASES = Object.freeze([
  "clean layout",
  "modern design",
  "user-friendly",
  "intuitive",
  "sleek",
  "minimalist",
  "good spacing",
  "nice typography",
  "visually appealing",
  "easy to use",
  "well-organized",
  "polished look"
]) as readonly string[];

export const VAGUE_PHRASES = Object.freeze([
  "avoid clutter",
  "keep it clean",
  "keep it simple",
  "don't overdo it",
  "be consistent",
  "avoid confusion",
  "too busy",
  "too much going on",
  "not intuitive",
  "bad ux",
  "poor ux"
]) as readonly string[];

export const UNLABELED_CONTROL_RISK = new RegExp("\\bicon[\\s-]*only|icons?\\s+(?:alone|symbols?\\s+alone)|icons?\\s+without\\s+(?:visible\\s+)?(?:text\\s+)?labels?|represented\\s+(?:solely\\s+)?by\\s+icons?|(?:icon|glyph|symbol|button|control)\\s+with\\s+(?:no|without)\\s+(?:a\\s+)?(?:visible\\s+)?(?:text\\s+)?labels?|(?:icon|glyph|symbol|button|control)\\s+(?:has|have|having)\\s+no\\s+(?:visible\\s+)?(?:text\\s+)?labels?|(?:icon|glyph|symbol|button|control)\\s+lack(?:s|ing)?\\s+(?:a\\s+)?(?:visible\\s+)?(?:text\\s+)?labels?|no\\s+(?:visible\\s+)?(?:text\\s+)?labels?\\s+(?:beside|next to|on|for|is visible)|no\\s+(?:visible\\s+)?(?:text\\s+)?labels?\\s+(?:are\\s+)?visible|(?:has|have)\\s+no\\s+(?:accompanying\\s+)?(?:visible\\s+)?(?:text\\s+)?labels?|no\\s+accompanying\\s+(?:visible\\s+)?(?:text\\s+)?labels?|lack(?:s|ing)?\\s+(?:an?\\s+|a\\s+)?(?:accompanying\\s+)?(?:visible\\s+)?(?:text\\s+)?labels?|no\\s+(?:visible\\s+)?accessible\\s+name|unlabeled\\s+(?:icon|button|control|nav)|rel(?:iance|ies|y)\\s+on\\s+(?:memorized\\s+)?(?:icon\\s+)?shapes?|\\bnaked\\s+icons?\\b|lacks?\\s+(?:an?\\s+)?accessible\\s+name|without\\s+(?:an?\\s+)?accessible\\s+name\\b", "i");
export const PIXEL_MEASUREMENT = new RegExp("\\b\\d+(?:\\.\\d+)?\\s*-?\\s*(?:px|pixel[s]?|pt|rem|em)\\b", "i");

export const EXEMPTION_PATTERNS = Object.freeze({
  domGroundTruth: new RegExp("\\b(?:dom|computed|contrast[\\s-]*ratio|accessibility\\s+tree|aria-|offsetwidth|offsetheight|getboundingclientrect|measured\\s+(?:from|via))\\b", "i"),
  contrastClause: new RegExp("\\b(?:instead\\s+of|rather\\s+than|avoids?|rejects?|unlike|in\\s+contrast\\s+to|could\\s+have|might\\s+(?:have\\s+)?(?:used|gone)|do\\s+not|does\\s+not|are\\s+not|is\\s+not|not\\s+(?:icon|going))\\b", "i"),
  positiveLabelPairing: new RegExp("\\b(?:paired?\\s+with|keeps?\\s+icons?\\s+paired|icons?\\s+(?:and|with)\\s+(?:text\\s+)?labels?|(?:text\\s+)?labels?\\s+(?:beside|next to|alongside)|instead\\s+of\\s+going\\s+icon[\\s-]*only)\\b", "i"),
});
