import { Component, DomainTag } from "./schema.js";
import type { RetagGoldField, RetagGoldPacket } from "./retag-gold.js";

type ImageUrlMap = ReadonlyMap<string, string>;

const FIELDS = ["components", "domainTags", "colorScheme", "mood", "visual.typePairing"] as const satisfies readonly RetagGoldField[];
const VOCABULARY = {
  components: [...Component.options],
  domainTags: [...DomainTag.options],
  colorScheme: ["light", "dark"],
} as const;

function escapeEmbeddedJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

/** Render a private standalone reviewer page for a validated gold packet. */
export function buildRetagGoldHtml(packet: RetagGoldPacket, imageUrls: ImageUrlMap): string {
  const data = {
    packet: {
      schemaVersion: packet.schemaVersion,
      artifactType: packet.artifactType,
      artifactId: packet.artifactId,
      selectionArtifactId: packet.selectionArtifactId,
      selectionSha256: packet.selectionSha256,
      fields: FIELDS,
      instructions: packet.instructions,
    },
    vocabulary: VOCABULARY,
    entries: packet.entries.map((entry) => ({
      entryId: entry.entryId,
      imageSha256: entry.imageSha256,
      imagePath: entry.imagePath,
      cohort: entry.cohort,
      stratum: entry.stratum,
      imageUrl: imageUrls.get(entry.entryId) ?? null,
    })),
  };
  const embedded = escapeEmbeddedJson(data);
  return `<!doctype html>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Retag gold reviewer</title>
<style>
:root{color-scheme:light dark;--bg:#f5f6f8;--panel:#fff;--ink:#17191d;--muted:#68707c;--line:#d9dde5;--accent:#356ae6;--danger:#c83e3e;--ok:#17834b}
@media(prefers-color-scheme:dark){:root{--bg:#111318;--panel:#191c22;--ink:#f0f2f5;--muted:#a8afbb;--line:#303641;--accent:#8aabff;--danger:#ff817d;--ok:#66d49b}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.45 ui-sans-serif,system-ui,sans-serif}header{position:sticky;top:0;z-index:5;border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--bg) 90%,transparent);backdrop-filter:blur(12px)}
.bar,main{max-width:1500px;margin:auto}.bar{padding:12px 22px;display:flex;align-items:center;gap:10px;flex-wrap:wrap}.bar h1{font-size:16px;margin:0}.spacer{flex:1}.progress{color:var(--muted)}
button,select,input,textarea{font:inherit}button{border:1px solid var(--line);border-radius:7px;color:var(--ink);background:var(--panel);padding:7px 11px;cursor:pointer}button:hover{border-color:var(--accent)}button.primary{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:650}button.danger{color:var(--danger)}
main{padding:18px 22px 100px}.notice{border:1px solid var(--line);border-radius:10px;background:var(--panel);padding:13px 16px;margin-bottom:16px}.notice.warn{border-color:#d49a36}.notice.error{border-color:var(--danger);color:var(--danger);white-space:pre-wrap}.hidden{display:none!important}
.settings{display:grid;grid-template-columns:minmax(220px,1fr) 160px auto;gap:10px;align-items:end}label{display:grid;gap:5px;color:var(--muted);font-size:12px;font-weight:650}input[type=text],textarea,select{width:100%;border:1px solid var(--line);border-radius:7px;padding:8px 9px;background:var(--panel);color:var(--ink)}textarea{min-height:58px;resize:vertical}
.entry{border:1px solid var(--line);border-radius:12px;background:var(--panel);margin:18px 0;overflow:hidden}.entry.complete{border-color:var(--ok)}.entry-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:12px 16px;border-bottom:1px solid var(--line)}.entry-head .id{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}.pill{border:1px solid var(--line);border-radius:99px;color:var(--muted);padding:2px 8px;font-size:11px;text-transform:uppercase}.pill.challenge{border-color:var(--accent);color:var(--accent)}
.entry-grid{display:grid;grid-template-columns:minmax(340px,1.25fr) minmax(420px,1fr);gap:18px;padding:16px;align-items:start}.shot{position:sticky;top:86px}.shot img{display:block;width:100%;max-height:78vh;object-fit:contain;border:1px solid var(--line);border-radius:8px;background:#7773;cursor:zoom-in}.missing{padding:40px 15px;border:1px dashed var(--line);color:var(--muted);text-align:center}.image-meta{color:var(--muted);font-size:11px;margin-top:7px;word-break:break-all}.fields{display:grid;gap:12px}.field{border:1px solid var(--line);border-radius:9px;padding:11px}.field.invalid{border-color:var(--danger)}.field-head{display:flex;align-items:center;gap:8px;margin-bottom:8px}.field-head strong{font-size:13px}.field-head .hint{color:var(--muted);font-size:11px;font-weight:400}.field-head select{margin-left:auto;width:auto;min-width:130px;padding:5px 7px}.checks{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:5px 9px;max-height:185px;overflow:auto;padding:4px 0}.checks label{display:flex;align-items:center;gap:7px;color:var(--ink);font-size:13px;font-weight:400}.checks input{accent-color:var(--accent)}.choice-row{display:flex;gap:7px;flex-wrap:wrap}.choice-row label{display:flex;align-items:center;gap:5px;color:var(--ink);border:1px solid var(--line);border-radius:7px;padding:7px 10px;font-weight:400;cursor:pointer}.subgrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.small{color:var(--muted);font-size:11px}#lightbox{position:fixed;inset:0;z-index:20;display:none;align-items:center;justify-content:center;padding:20px;background:#000d;cursor:zoom-out}#lightbox.open{display:flex}#lightbox img{max-width:100%;max-height:100%;object-fit:contain}@media(max-width:900px){.entry-grid{grid-template-columns:1fr}.shot{position:static}.settings{grid-template-columns:1fr}}
</style>
<header><div class="bar"><h1>Retag gold reviewer</h1><span class="progress" id="progress">0 / 0 complete</span><span class="spacer"></span><button id="jump">Next incomplete</button><button id="clear" class="danger">Clear draft</button><button id="copy" class="primary">Copy JSON</button><button id="download">Download JSON</button></div></header>
<main><div class="notice warn"><strong>Evidence discipline:</strong> use the screenshot and available DOM evidence only. Do not seed from the corpus or a model. Screenshot-only font guesses are abstentions; mood is OOV until its vocabulary is frozen.</div><div class="notice" id="instructions"></div><div class="notice settings"><label>Reviewer ID<input id="actor" type="text" placeholder="e.g. alice" autocomplete="off"></label><label>Role<select id="role"><option value="gold">gold</option><option value="qa">qa</option></select></label><span class="small">Use different IDs for the two independent submissions.</span></div><div class="notice error hidden" id="errors"></div><section id="entries"></section></main><div id="lightbox"><img alt="Expanded screenshot"></div>
<script>
const DATA=${embedded}, FIELDS=DATA.packet.fields, KEY="retag-gold-reviewer:"+DATA.packet.selectionSha256, state={actorId:"",reviewerRole:"gold",labels:{}};
const $=id=>document.getElementById(id), field=(id,name)=>state.labels[id][name];
function blank(){return{status:"",evidenceSource:"image",values:[],value:"",note:"",display:"",body:"",notes:"",candidates:""}}
function blankLabel(){return Object.fromEntries(FIELDS.map(f=>[f,blank()]))}
function init(){DATA.entries.forEach(e=>state.labels[e.entryId]=blankLabel());try{const old=JSON.parse(localStorage.getItem(KEY)||"null");if(old&&old.labels)Object.assign(state,old)}catch(_){}$("actor").value=state.actorId||"";$("role").value=state.reviewerRole||"gold"}
function save(){state.actorId=$("actor").value.trim();state.reviewerRole=$("role").value;try{localStorage.setItem(KEY,JSON.stringify(state))}catch(_){}updateProgress()}
function node(tag,props={},text=""){const n=document.createElement(tag);for(const [key,value] of Object.entries(props)){if(key==="dataset")Object.assign(n.dataset,value);else n[key]=value}if(text)n.textContent=text;return n}
function label(text,control){const l=node("label");l.append(control,document.createTextNode(text));return l}
function statusOptions(name){return name==="mood"?["none","abstain","oov"]:["present","none","abstain","oov"]}
function vocab(name){return name==="components"?DATA.vocabulary.components:name==="domainTags"?DATA.vocabulary.domainTags:name==="colorScheme"?DATA.vocabulary.colorScheme:[]}
function input(id,name,key,placeholder){const i=node("input",{type:"text",value:field(id,name)[key]||"",placeholder});i.oninput=()=>{field(id,name)[key]=i.value;save()};return i}
function note(id,name){const t=node("textarea",{placeholder:"Required when abstaining or recording OOV"});t.value=field(id,name).note||"";t.oninput=()=>{field(id,name).note=t.value;save()};return t}
function renderField(id,name){const root=document.querySelector('[data-entry="'+CSS.escape(id)+'"] [data-field="'+CSS.escape(name)+'"]');if(!root)return;root.textContent="";const v=field(id,name),head=node("div",{className:"field-head"}),hint=name==="visual.typePairing"?"DOM required for present":name==="mood"?"OOV until vocabulary freeze":"";head.append(node("strong",{},name),node("span",{className:"hint"},hint));const select=node("select");select.append(node("option",{value:""},"choose status"));statusOptions(name).forEach(s=>select.append(node("option",{value:s},s)));select.value=v.status;select.onchange=()=>{v.status=select.value;v.values=[];v.value="";v.candidates="";v.note="";save();renderField(id,name)};head.append(select);root.append(head);const body=node("div");
if(v.status==="present"&&(name==="components"||name==="domainTags")){const checks=node("div",{className:"checks"});vocab(name).forEach(option=>{const box=node("input",{type:"checkbox",checked:v.values.includes(option)});box.onchange=()=>{v.values=v.values.filter(x=>x!==option);if(box.checked)v.values.push(option);save()};checks.append(label(option,box))});body.append(checks)}
else if(v.status==="present"&&name==="colorScheme"){const choices=node("div",{className:"choice-row"});vocab(name).forEach(option=>{const radio=node("input",{type:"radio",name:id+"-color",value:option,checked:v.value===option});radio.onchange=()=>{v.value=option;save()};choices.append(label(option,radio))});body.append(choices)}
else if(v.status==="present"&&name==="visual.typePairing"){const grid=node("div",{className:"subgrid"});grid.append(input(id,name,"display","display font or null"),input(id,name,"body","body font or null"));body.append(grid);body.append(node("label",{},"Evidence source"));const evidence=node("select");evidence.append(node("option",{value:"dom"},"DOM evidence"),node("option",{value:"both"},"Image + DOM"));evidence.value=v.evidenceSource==="both"?"both":"dom";evidence.onchange=()=>{v.evidenceSource=evidence.value;save()};body.append(evidence);body.append(node("label",{},"Notes"),input(id,name,"notes","optional typographic notes"))}
else if(v.status==="present"&&name==="mood")body.append(node("div",{className:"small"},"Mood has no frozen vocabulary. Choose OOV and record the concrete phrase."));
else if(v.status==="oov"){body.append(node("label",{},"Candidate(s), one per line or comma-separated"),input(id,name,"candidates","e.g. observability"),node("label",{},"Why the vocabulary is inadequate"),note(id,name))}
else if(v.status==="abstain")body.append(node("label",{},"Reason for abstaining"),note(id,name));root.classList.toggle("invalid",!v.status);root.append(body)}
function renderEntry(e,index){const card=node("article",{className:"entry",id:"entry-"+index,dataset:{entry:e.entryId}}),head=node("div",{className:"entry-head"});head.append(node("strong",{},String(index+1).padStart(2,"0")),node("span",{className:"id"},e.entryId),node("span",{className:"pill "+e.cohort},e.cohort),node("span",{className:"pill"},e.stratum));card.append(head);const grid=node("div",{className:"entry-grid"}),shot=node("div",{className:"shot"});if(e.imageUrl){const image=node("img",{src:e.imageUrl,alt:"Screenshot for "+e.entryId});image.onclick=ev=>{ev.stopPropagation();$("lightbox").classList.add("open");$("lightbox").firstElementChild.src=e.imageUrl};shot.append(image)}else shot.append(node("div",{className:"missing"},"Image path unavailable"));shot.append(node("div",{className:"image-meta"},e.imagePath+" · SHA-256 "+e.imageSha256));grid.append(shot);const fields=node("div",{className:"fields"});FIELDS.forEach(name=>fields.append(node("div",{className:"field",dataset:{field:name}})));grid.append(fields);card.append(grid);$("entries").append(card);FIELDS.forEach(name=>renderField(e.entryId,name))}
function complete(e){return FIELDS.every(name=>Boolean(field(e.entryId,name).status))}function updateProgress(){const done=DATA.entries.filter(complete).length;$("progress").textContent=done+" / "+DATA.entries.length+" entries complete";DATA.entries.forEach(e=>{const c=document.querySelector('[data-entry="'+CSS.escape(e.entryId)+'"]');if(c)c.classList.toggle("complete",complete(e))})}
function candidates(raw){return[...new Set(raw.split(",").flatMap(x=>x.split(String.fromCharCode(10))).map(x=>x.trim()).filter(Boolean))]}function build(){const errors=[],labels=[];if(!state.actorId)errors.push("Reviewer ID is required.");DATA.entries.forEach(e=>{const fields={};FIELDS.forEach(name=>{const r=field(e.entryId,name);if(!r.status){errors.push(e.entryId+": choose a status for "+name);return}const o={status:r.status,evidenceSource:r.evidenceSource};if(r.status==="present"){if(name==="mood")errors.push(e.entryId+": mood must be recorded as OOV until its vocabulary is frozen");else if(name==="components"||name==="domainTags"){if(!r.values.length)errors.push(e.entryId+": choose at least one "+name);else o.value=r.values}else if(name==="colorScheme"){if(!r.value)errors.push(e.entryId+": choose light or dark");else o.value=r.value}else if(name==="visual.typePairing"){if(r.evidenceSource!=="dom"&&r.evidenceSource!=="both")errors.push(e.entryId+": type pairing needs DOM evidence");o.value={display:r.display.trim()||null,body:r.body.trim()||null,notes:r.notes.trim()||undefined}}}else if(r.status==="oov"){o.oov=candidates(r.candidates);if(!o.oov.length)errors.push(e.entryId+": add an OOV candidate for "+name);if(!r.note.trim())errors.push(e.entryId+": explain the OOV candidate for "+name);else o.note=r.note.trim()}else if(r.status==="abstain"){if(!r.note.trim())errors.push(e.entryId+": explain the abstention for "+name);else o.note=r.note.trim()}fields[name]=o});labels.push({entryId:e.entryId,imageSha256:e.imageSha256,fields})});if(errors.length)return{errors,payload:null};return{errors:[],payload:{schemaVersion:"1.0",artifactType:"retag-gold-submission",artifactId:"retag-gold-submission-"+state.actorId+"-v1",selectionArtifactId:DATA.packet.selectionArtifactId,selectionSha256:DATA.packet.selectionSha256,submissionVersion:1,actorId:state.actorId,actorKind:"human",reviewerRole:state.reviewerRole,sealedAt:new Date().toISOString(),labels}}}
function showErrors(errors){const box=$("errors");box.textContent=errors.slice(0,30).join(String.fromCharCode(10))+(errors.length>30?String.fromCharCode(10)+"…":"");box.classList.toggle("hidden",!errors.length);if(errors.length)scrollTo({top:0,behavior:"smooth"})}async function copyJson(){const r=build();showErrors(r.errors);if(!r.payload)return;const text=JSON.stringify(r.payload,null,2);try{await navigator.clipboard.writeText(text);alert("Submission JSON copied to the clipboard.")}catch(_){const a=node("textarea",{value:text});document.body.append(a);a.select();document.execCommand("copy");a.remove();alert("Submission JSON copied. If it was not, use Download JSON.")}}function downloadJson(){const r=build();showErrors(r.errors);if(!r.payload)return;const blob=new Blob([JSON.stringify(r.payload,null,2)+String.fromCharCode(10)],{type:"application/json"}),a=node("a",{href:URL.createObjectURL(blob),download:r.payload.artifactId+".json"});a.click();URL.revokeObjectURL(a.href)}function clearDraft(){if(confirm("Clear this reviewer draft?")){localStorage.removeItem(KEY);location.reload()}}function jumpNext(){const e=DATA.entries.find(x=>!complete(x));if(e)$("entry-"+DATA.entries.indexOf(e)).scrollIntoView({behavior:"smooth",block:"start"})}
init();DATA.packet.instructions.forEach(x=>$('instructions').append(node("div",{},x)));DATA.entries.forEach(renderEntry);updateProgress();$("actor").oninput=save;$("role").onchange=save;$("copy").onclick=copyJson;$("download").onclick=downloadJson;$("clear").onclick=clearDraft;$("jump").onclick=jumpNext;$("lightbox").onclick=ev=>{if(ev.target===ev.currentTarget)$("lightbox").classList.remove("open")};
</script>`;
}
